[package]
name = "rusty_directory_flattener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
regex = "1.7.0"
users = "0.11"
fs_extra = "1.2.0"
